project_id = "fskstajvuoviicfjfcai"

[functions.evolution-webhook]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-open-conversation]
verify_jwt = false

[functions.whatsapp-transfer]
verify_jwt = false

[functions.cnj-lookup]
verify_jwt = false

[functions.ai-agent-reply]
verify_jwt = false

[functions.whatsapp-media-process]
verify_jwt = false

[functions.appointment-notify]
verify_jwt = false

[functions.brevo-webhook]
verify_jwt = false

[functions.campaign-worker]
verify_jwt = false



[functions.admin-create-team-member]
verify_jwt = false
