
INSERT INTO public.site_settings (key, value) VALUES
  ('whatsapp_number', '5500000000000'),
  ('whatsapp_message', 'Olá, gostaria de solicitar um atendimento jurídico.'),
  ('hero_badge', 'Advocacia Criminal Especializada'),
  ('hero_title', 'Defesa Criminal com Excelência e Dedicação'),
  ('hero_title_highlight', 'Excelência'),
  ('hero_subtitle', 'Atuação estratégica em Direito Penal. Sigilo absoluto, atendimento humanizado e defesa técnica rigorosa para proteger seus direitos e sua liberdade.'),
  ('hero_cta_primary', 'Solicitar Atendimento'),
  ('hero_cta_secondary', 'Conheça Nossa Atuação'),
  ('hero_stat_1_number', '15+'),
  ('hero_stat_1_label', 'Anos de Experiência'),
  ('hero_stat_2_number', '1000+'),
  ('hero_stat_2_label', 'Casos Atendidos'),
  ('hero_stat_3_number', '24h'),
  ('hero_stat_3_label', 'Atendimento Urgente'),
  ('hero_stat_4_number', '100%'),
  ('hero_stat_4_label', 'Sigilo Garantido'),
  ('about_eyebrow', 'Sobre o Escritório'),
  ('about_title', 'Advocacia Criminal de Excelência'),
  ('about_title_highlight', 'Excelência'),
  ('about_paragraph_1', 'O escritório Lindomberto Moraes – Advocacia Criminal é especializado exclusivamente em Direito Penal, oferecendo defesa técnica qualificada para clientes em todo o Brasil.'),
  ('about_paragraph_2', 'Com mais de 15 anos de experiência, nossa atuação é pautada pela ética inabalável, pelo respeito ao sigilo profissional e pelo compromisso com a defesa dos direitos e garantias fundamentais de nossos clientes.'),
  ('about_paragraph_3', 'Entendemos que cada caso é único e merece atenção personalizada. Por isso, oferecemos um atendimento humanizado, onde o cliente é ouvido, respeitado e mantido informado sobre todos os passos do seu processo.'),
  ('cta_badge', 'Atendimento Sigiloso e Imediato'),
  ('cta_title', 'Precisa de um Advogado Criminalista?'),
  ('cta_title_highlight', 'Advogado Criminalista?'),
  ('cta_subtitle', 'Não enfrente essa situação sozinho. Entre em contato agora mesmo e receba orientação jurídica especializada com total sigilo e agilidade.'),
  ('cta_button', 'Solicitar Atendimento via WhatsApp'),
  ('footer_description', 'Defesa criminal especializada com ética, sigilo e dedicação. Atuamos em todo o Brasil com atendimento humanizado.'),
  ('footer_oab', 'OAB/SP 000.000'),
  ('contact_hours', 'Seg - Sex: 9h às 18h')
ON CONFLICT (key) DO NOTHING;
