// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fskstajvuoviicfjfcai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZza3N0YWp2dW92aWljZmpmY2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1NzQxMjAsImV4cCI6MjA4OTE1MDEyMH0.mOxfDN3G9UIf6HSrU4tsTIjlesyTlvnEDLMd6HhyzLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});